spring:
  h2:
    console:
      enabled: false
      path: /h2-console
  jpa:
    generate-ddl: true
    database: h2
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: create-drop
